FROM python:3.11-slim
RUN apt-get -y update
RUN apt-get install -y --no-install-recommends \
  build-essential \
  libffi-dev \
  libpq-dev \
  bash
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
COPY ./is_project/requirements.txt ./
RUN pip install pip==23.0
RUN pip install --no-cache-dir -r requirements.txt
ADD . /pedestrian